import type { Metadata } from "next";
import "./globals.css";

// 使用系统字体，避免网络下载问题
const fontSans = {
  variable: "--font-sans",
};

const fontMono = {
  variable: "--font-mono",
};

export const metadata: Metadata = {
  title: "申请审核界面",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased font-sans"
      >
        {children}
      </body>
    </html>
  );
}
