server:
  port: 8080

spring:
  application:
    name: customer-questionnaire-service
  
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3307/audit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
=======
    url: jdbc:mysql://47.99.213.155:3306/audit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: manba
    password: 114514
>>>>>>> 13b8b441ad6af1e54e0150241a9e82667a73d54b
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

logging:
  level:
    com.audit: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE