server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:ssl/audit-keystore.p12
    key-store-password: auditpass
    key-store-type: PKCS12
    key-alias: audit-server
    key-password: auditpass

spring:
  application:
    name: customer-questionnaire-service
  
  datasource:
    url: jdbc:mysql://47.99.213.155:3306/audit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # url: jdbc:mysql://localhost:3307/audit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # username: root
    #password: 123456
    username: manba
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

# 审核任务配置
audit:
  task:
    max-batch-size: 10

# JWT配置
jwt:
  secret: audit-system-jwt-secret-key-for-sm4-encryption-2024-very-long-secret
  expiration: 7200000  # 2小时，单位毫秒

logging:
  level:
    com.audit: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE