# 开发环境配置 - 使用HTTP避免SSL配置问题
server:
  port: 8080
  # 暂时禁用SSL用于调试
  
spring:
  application:
    name: customer-questionnaire-service
  
  datasource:
    url: jdbc:mysql://47.99.213.155:3306/audit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: manba
    password: 114514
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

# JWT配置
jwt:
  secret: audit-system-jwt-secret-key-for-sm4-encryption-2024-very-long-secret
  expiration: 7200000  # 2小时，单位毫秒

# 审核任务配置
audit:
  task:
    max-batch-size: 10

logging:
  level:
    com.audit: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Kafka配置
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

# DeepSeek AI API配置
deepseek:
  api:
    key: ${DEEPSEEK_API_KEY:your-deepseek-api-key}